spring.config.activate.on-profile=postgres

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/infinitygodiagnostics}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DATABASE_USERNAME:infinitygo_app}
spring.datasource.password=${DATABASE_PASSWORD:infinitygo_app}

spring.flyway.enabled=true

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
