spring.application.name=diagnostic-backend
spring.profiles.default=postgres
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

app.security.admin.username=${ADMIN_USERNAME:admin}
app.security.admin.password=${ADMIN_PASSWORD:change-me-now}

server.error.include-message=always
